### ISSUE TITLE
chat.getRoomMessages should accept query parameters

### ISSUE THREAD

**Issue by hitochan777** [shirasudon/go-chat#20]
Currently `chat.getRoomMessages` is called when **GET** requests are received on `/chat/rooms/:room_id/messages`. But it seems like it only parses **JSON** request body (See [here](https://github.com/shirasudon/go-chat/blob/e72b946c0156323a02f6fd862fc3a525b2039266/chat/action/query.go#L9))  as you can see below: 
```
type QueryRoomMessages struct {
	RoomID uint64    `json:"room_id"`
	Before time.Time `json:"before"`
	Limit  int       `json:"limit"`
}
```
As specified in [HTTP spec](https://tools.ietf.org/html/rfc2616#section-9.3), requests should be able to specify resources they require by **Request-URI only**. 
That is, instead of using `json` as struct tags, what about using `query` as below?
```
type QueryRoomMessages struct {
	RoomID uint64    `query:"room_id"`
	Before time.Time `query:"before"`
	Limit  int       `query:"limit"`
}
```
I referred to [Echo documentation](https://echo.labstack.com/guide/request) by the way.

**Comment by hitochan777** [comment]
It seems that Echo cannot parse string to `time.Time`.
Workaround is to implement `Echo#BindUnmarshale` for custom time type.
What do you think is the best approach?

**Comment by mzki** [comment]
My opinion is that the struct type should be the form below (but not compiled).
Using `query` tags except that `room_id`.
`time.Time` type is implement `echo.BindUnmarshaler` interface.

```golang
type QueryRoomMessages struct {
	RoomID uint64    
	Before Timestamp `query:"before"
	Limit  int       `query:"limit"
}

// implement echo.BindUnmarshaler interface.
type Timestamp time.Time
```

As you mentioned, `query` tags are preferred for that struct type. 
but `room_id` is a identifier for the resources and others are not.
The URI request would be
`/chat/rooms/:room_id/messages?before=xxx&limit=yyy`, 
where `room_id` is a identifier for the resources, 
`before` and `limit` are query parameters to adjust queried resources.
`query` tag is not preferred for `room_id`.

Finally, I think that I will implement `query` tags for that struct.
But It will be done at later because I'm some busy now.

**Comment by mzki** [comment]
This issue is implemented and merged.
close.
