### ISSUE TITLE
How to get a list of readAt for all the members in a room?

### ISSUE THREAD

**Issue by hitochan777** [shirasudon/go-chat#23]
@mzki Currently it seems that there is no way to get a list of `readAt` for all the members in a room.
Is it the case?

**Comment by mzki** [comment]
Yes that's it.

Probably, you want to get *read count* for the chat messages?
If so, I think it is better for implementing *read count* for `queried.Message` .

What your usecase here?

**Comment by hitochan777** [comment]
@mzki right. I am thinking of showing read counts for all the messages. 
We can achieve this either on the server and client side.
I think implementing it on the client side is preferable because computing read counts on the server side is too much of a burden.
We can derive read counts for all the messages by `readAt` for all the members in a room.

**Comment by mzki** [comment]
@hitochan777 OK. I will implement `readAt` for queried room members. You can use `readAt` to calculate read counts for the chat messages.

**Comment by hitochan777** [comment]
thanks!

**Comment by mzki** [comment]
@hitochan777 The plan is changed. On the client side, it is a hard to calculate *read counts* for the chat messages by using `readAt`. The chat messages are often not fully loaded on the client side. The calculation of the *read counts* is required on every time to load the messages.

Instead of that, I recommends that the *read counts* are calculated on the server side.
The *read counts* are contained in `queried.Message`, and you can get those from GET request. 

I will proceed with the implementation of calculating `read counts` on the server side.

**Comment by mzki** [comment]
This issue is implemented. close.
