### ISSUE TITLE
Add a URI to serve index.html?

### ISSUE THREAD

**Issue by hitochan777** [shirasudon/go-chat#29]
Can you please add a url to serve html files?
There are two possibilities I can think ok:
1. make specific path (e.g., `/app`) that returns `public/index.html`.
2. move REST API under `/api` and `/` returns `public/index.html`
Currently `/*` is  reserved for static files but I don't think it is safe to do that, cuz clients 
can access any files (e.g., Gopkg.toml)

**Comment by mzki** [comment]
@hitochan777 It is better that making the URI prefixes is configurable by external config file such as `toml`, because I think setting the URI prefixes for the asset files or API is the user matters.

By [echo documentation](https://echo.labstack.com/guide/static-files), we can configure both of the URI path and the root path for the assets. It can allow to serve the static files only under the specific root path on the specific URI.

I can provide a feature to configure the URI prefixes with external `toml` file.

**Comment by hitochan777** [comment]
OK. That would be perfect!

**Comment by mzki** [comment]
This issue is implemented. closing.
